### ISSUE TITLE
Importing cupy causes `Segmentation fault` after importing chainerx

### ISSUE THREAD

**Issue by okapies** [chainer/chainer#5844]
Importing `cupy` causes `Segmentation fault` after importing `chainerx` if `LD_LIBRARY_PATH` is not configured correctly (in other words, cupy *or* chainerx fail to find `libcudnn.so`). It also causes `import chainer` to fail.

## Environment
- Chainer version: `master` branch (`5537879`)
- CuPy version: `6.0.0b1`
- OS/Platform: Ubuntu 16.04.4 LTS
- CUDA/cuDNN version: v7.2.1-cuda92

## Reproduction
1. Installing cuDNN (using `cudnnenv`):
```bash
pip install cudnnenv
export PATH="/usr/local/cuda-9.2/bin:$PATH"
export LD_LIBRARY_PATH=~/.cudnn/active/cuda/lib64:$LD_LIBRARY_PATH
export CPATH=~/.cudnn/active/cuda/include:$CPATH
export LIBRARY_PATH=~/.cudnn/active/cuda/lib64:$LIBRARY_PATH
cudnnenv install v7.2.1-cuda92
```

2. Installing CuPy and Chainer with ChainerX:
```bash
CUDA_PATH=/usr/local/cuda-9.2 pip install cupy==6.0.0b1
git clone https://github.com/chainer/chainer.git
cd chainer
export CHAINER_BUILD_CHAINERX=1
export CHAINERX_BUILD_CUDA=1
export CUDNN_ROOT_DIR=~/.cudnn/active
export MAKEFLAGS=-j32
pip install -e .
```

3. Unsetting `LD_LIBRARY_PATH`:
```bash
$ ldd ~/chainer/chainerx/libchainerx.so
	linux-vdso.so.1 =>  (0x00007ffc11aad000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fcfd69ef000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fcfd67d2000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007fcfd65ca000)
	libcublas.so.9.2 => /usr/local/cuda-9.2/lib64/libcublas.so.9.2 (0x00007fcfd2b97000)
	libcudnn.so.7 => /home/user/.cudnn/active/cuda/lib64/libcudnn.so.7 (0x00007fcfc1602000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fcfc1280000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fcfc0f77000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fcfc0d61000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fcfc0997000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fcfdc924000)
$ unset LD_LIBRARY_PATH
$ ldd ~/chainer/chainerx/libchainerx.so
	linux-vdso.so.1 =>  (0x00007fff70fdb000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f638cee7000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f638ccca000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f638cac2000)
	libcublas.so.9.2 => /usr/local/cuda-9.2/lib64/libcublas.so.9.2 (0x00007f638908f000)
	libcudnn.so.7 => not found
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f6388d0d000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f6388a04000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f63887ee000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f6388424000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f6392e1c000)
```

4. Importing `chainerx` before importing `cupy` causes `Segmentation fault`
```bash
$ python -c "import cupy"
(Nothing happens)
$ python -c "import chainerx; import cupy"
Segmentation fault (core dumped)
$ python -c "import chainer"
Segmentation fault (core dumped)
```

Here is a `py-bt` stack trace on `gdb`:

<details><summary>click here</summary>

```python
Traceback (most recent call first):
  <built-in method create_dynamic of module object at remote 0x7ffff7081558>
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 922, in create_module
  File "<frozen importlib._bootstrap>", line 571, in module_from_spec
  File "<frozen importlib._bootstrap>", line 658, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  <built-in method __import__ of module object at remote 0x7ffff70a9cd8>
  <built-in method exec_dynamic of module object at remote 0x7ffff7081558>
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 929, in exec_module
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  <built-in method __import__ of module object at remote 0x7ffff70a9cd8>
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1023, in _handle_fromlist
  File "/home/user/.pyenv/versions/3.6.5-debug/lib/python3.6/site-packages/cupy/cuda/compiler.py", line 11, in <module>
    from cupy.cuda import device
  <built-in method exec of module object at remote 0x7ffff70a9cd8>
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  <built-in method __import__ of module object at remote 0x7ffff70a9cd8>
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1023, in _handle_fromlist
  File "/home/user/.pyenv/versions/3.6.5-debug/lib/python3.6/site-packages/cupy/cuda/__init__.py", line 4, in <module>
    from cupy.cuda import compiler  # NOQA
  <built-in method exec of module object at remote 0x7ffff70a9cd8>
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  <built-in method __import__ of module object at remote 0x7ffff70a9cd8>
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  <built-in method __import__ of module object at remote 0x7ffff70a9cd8>
  <built-in method exec_dynamic of module object at remote 0x7ffff7081558>
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 929, in exec_module
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  <built-in method __import__ of module object at remote 0x7ffff70a9cd8>
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1023, in _handle_fromlist
  File "/home/user/.pyenv/versions/3.6.5-debug/lib/python3.6/site-packages/cupy/core/__init__.py", line 1, in <module>
    from cupy.core import core  # NOQA
  <built-in method exec of module object at remote 0x7ffff70a9cd8>
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  <built-in method __import__ of module object at remote 0x7ffff70a9cd8>
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1023, in _handle_fromlist
  File "/home/user/.pyenv/versions/3.6.5-debug/lib/python3.6/site-packages/cupy/__init__.py", line 11, in <module>
    from cupy import core  # NOQA
  <built-in method exec of module object at remote 0x7ffff70a9cd8>
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<string>", line 1, in <module>
```

</details>

**Comment by okapies** [comment]
It still happens on the current `master`.

**Comment by okapies** [comment]
It still happens too.

**Comment by okapies** [comment]
The issue has been solved in the current `master`. It seems it is fixed in #7518.

```
$ python -c "import chainerx; import cupy"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/user/chainer/chainerx/__init__.py", line 22, in <module>
    from chainerx import _core
ImportError: libcudnn.so.7: cannot open shared object file: No such file or directory
```
