### ISSUE TITLE
Raise CUDNN_STATUS_BAD_PARAMS in NStepLSTM when it takes a sequence whose a length is one

### ISSUE THREAD

**Issue by himkt** [chainer/chainer#7545]
NStepLSTM using cuDNN raise `CUDNN_STATUS_BAD_PARAMS` when
it takes a sequence whose length is one.
If using NStepLSTM on CPU or GPU without cuDNN, there is no problem.
(So, it's the cuDNN specific problem)

As @chantera noted, this problem can be avoided to use `ys`.
(https://docs.chainer.org/en/stable/reference/generated/chainer.links.NStepLSTM.html#chainer.links.NStepLSTM.forward)
However, I think it is difficult for me to find this workaround.

If this problem causes because of cuDNN's specification,
it would be better to let users know when the input is wrong.

* Conditions

```
Platform: Linux-4.4.0-1084-aws-x86_64-with-debian-stretch-sid
Chainer: 7.0.0a1
NumPy: 1.15.4
CuPy:
  CuPy Version          : 7.0.0a1
  CUDA Root             : /usr/local/cuda
  CUDA Build Version    : 10010
  CUDA Driver Version   : 10010
  CUDA Runtime Version  : 10010
  cuDNN Build Version   : 7500
  cuDNN Version         : 7500
  NCCL Build Version    : 2402
  NCCL Runtime Version  : 2402
iDeep: Not Available
```

* Code to reproduce

@chantera wrote the code to reproduce. 
(https://github.com/himkt/pyner/issues/38#issuecomment-502407133)

```
import chainer
from chainer.backends import cuda
import chainer.functions as F
import numpy as np


class Model(chainer.Chain):

    def __init__(self, n_vocab, n_units, n_tags, impl=0):
        super().__init__()
        with self.init_scope():
            self.embed = chainer.links.EmbedID(n_vocab, n_units)
            self.bilstm = chainer.links.NStepBiLSTM(1, n_units, n_units, 0.5)
            self.linear = chainer.links.Linear(n_units * 2, n_tags)
        self.impl = impl

    def forward(self, xs):
        hy, cy, hs = self.bilstm(None, None, [self.embed(x) for x in xs])
        if self.impl > 0:
            hs = hy.transpose([1, 0, 2]).reshape(len(xs), -1)
            ys = self.linear(hs)
        else:
            d = hs[0].shape[-1] // 2
            features = []
            for h in hs:
                feature = F.concat((h[-1, :d], h[0, d:]), axis=0)
                features.append(feature)
            ys = self.linear(F.vstack(features))
        return ys

    def __str__(self):
        return "{}(impl={})".format(self.__class__.__name__, self.impl)


if __name__ == '__main__':
    chainer.config.use_cudnn = 'always'
    n_vocab = 1000
    n_tags = 128
    n_units = 200

    input0 = (10, 2, 4, 5, 1, 6)
    input1 = (1,)
    model0 = Model(n_vocab, n_units, n_tags, impl=0)
    model1 = Model(n_vocab, n_units, n_tags, impl=1)

    def generate_data(lengths):
        xs = [np.random.randint(n_vocab, size=l) for l in lengths]
        ys = np.random.randint(n_tags, size=len(lengths))
        return xs, ys

    def run(model, lengths):
        print("RUN: model={}, lengths={}".format(model, lengths))
        model.to_gpu()
        model.cleargrads()
        xs, ts = generate_data(lengths)
        ys = model.forward([cuda.to_gpu(x) for x in xs])
        ts = cuda.to_gpu(ts)
        loss = F.softmax_cross_entropy(ys, ts, ignore_label=-1)
        print("loss", loss)
        loss.backward()

    run(model0, input0)
    run(model1, input0)
    run(model0, input1)
    run(model1, input1)  # cupy.cuda.cudnn.CuDNNError: CUDNN_STATUS_BAD_PARAM
```

* Error messages, stack traces, or logs

```
Traceback (most recent call last):
  File "test.py", line 65, in <module>
    run(model1, input1)  # cupy.cuda.cudnn.CuDNNError: CUDNN_STATUS_BAD_PARAM
  File "test.py", line 60, in run
    loss.backward()
  File "/home/ubuntu/work/github.com/himkt/pyner/venv/lib/python3.7/site-packages/chainer/variable.py", line 1433, in backward
    _backprop_to_all([(node, grad_var)], retain_grad, loss_scale)
  File "/home/ubuntu/work/github.com/himkt/pyner/venv/lib/python3.7/site-packages/chainer/variable.py", line 1649, in _backprop_to_all
    func, target_input_indexes, out_grad, in_grad, is_debug)
  File "/home/ubuntu/work/github.com/himkt/pyner/venv/lib/python3.7/site-packages/chainer/_backprop_utils.py", line 140, in backprop_step
    _reraise_with_stack(func, e)
  File "/home/ubuntu/work/github.com/himkt/pyner/venv/lib/python3.7/site-packages/chainer/_backprop_utils.py", line 138, in backprop_step
    target_input_indexes, grad_outputs)
  File "/home/ubuntu/work/github.com/himkt/pyner/venv/lib/python3.7/site-packages/chainer/function.py", line 209, in backward
    gxs = self._function.backward(in_data, grad_out_data)
  File "/home/ubuntu/work/github.com/himkt/pyner/venv/lib/python3.7/site-packages/chainer/functions/connection/n_step_rnn.py", line 325, in backward
    dhy, dcy, dys, self.lengths)
  File "cupy/cudnn.pyx", line 1094, in cupy.cudnn.rnn_backward_data
  File "cupy/cuda/cudnn.pyx", line 2186, in cupy.cuda.cudnn.RNNBackwardData
  File "cupy/cuda/cudnn.pyx", line 732, in cupy.cuda.cudnn.check_status
cupy.cuda.cudnn.CuDNNError: CUDNN_STATUS_BAD_PARAM
```

- related: https://github.com/himkt/pyner/issues/38

**Comment by kmaehashi** [comment]
I've checked this issue and found that the cause is that `strides` of `ys` and `dys` given to `RNNBackwardData` are different to each other. They are both C-contiguous if length is one, so it slips this parameter validation:
https://github.com/cupy/cupy/blob/b29253737305b17835b2e6fabdd89bc27a869a9d/cupy/cudnn.pyx#L1059
After copying `ys` and `dys` to new array in the above code (to make them have same strides), the error no longer occur. I think it's an issue of CuPy side.

**Comment by kmaehashi** [comment]
This issue has been solved in CuPy side https://github.com/cupy/cupy/pull/2261
